// <auto-generated />
namespace capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nuovocampotitolocalsserecensioni : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nuovocampotitolocalsserecensioni));
        
        string IMigrationMetadata.Id
        {
            get { return "202310311134285_nuovo-campo-titolo-calsse-recensioni"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
